### ISSUE TITLE
Bug d'affichage sur une opération pour un gestionnaire de série

### ISSUE THREAD

**Issue by flo7894** [InseeFr/Bauhaus#1020]
Le problème est se produit lorsque l'utilisateur possède le rôle de gestionnaire de série, sans posséder celui d’administrateur.

Dans ce cas l'affichage d'une opération provoque une erreur côté Front indiquant
![Image](https://github.com/user-attachments/assets/54a65f24-0efa-4bda-a332-9018222ffe44)

**Comment by CatherineGoillot** [comment]
Je me suis enlevée en tant qu'administratrice RMéS et je me mise en tant que gestionnaire.
Quand j'essaie d'afficher une opération, j'ai le message suivant 
![Image](https://github.com/user-attachments/assets/f4cb2f03-cb7f-4cff-b846-092c944cea0f)

Et dans la console :  

TypeError: s.series.creators is undefined
    a https://gestion-metadonnees.developpement2.insee.fr/assets/index-DSJrezYZ.js:1
    Kb https://gestion-metadonnees.developpement2.insee.fr/assets/index-FGZCz9p2.js:1008
    Kb https://gestion-metadonnees.developpement2.insee.fr/assets/index-FGZCz9p2.js:1008
    e3 https://gestion-metadonnees.developpement2.insee.fr/assets/index-FGZCz9p2.js:57
    hse https://gestion-metadonnees.developpement2.insee.fr/assets/index-FGZCz9p2.js:59
    fse https://gestion-metadonnees.developpement2.insee.fr/assets/index-FGZCz9p2.js:59
    TEe https://gestion-metadonnees.developpement2.insee.fr/assets/index-FGZCz9p2.js:59
    IC https://gestion-metadonnees.developpement2.insee.fr/assets/index-FGZCz9p2.js:59
    G$ https://gestion-metadonnees.developpement2.insee.fr/assets/index-FGZCz9p2.js:59
    use https://gestion-metadonnees.developpement2.insee.fr/assets/index-FGZCz9p2.js:59
    k https://gestion-metadonnees.developpement2.insee.fr/assets/index-FGZCz9p2.js:44
    G https://gestion-metadonnees.developpement2.insee.fr/assets/index-FGZCz9p2.js:44
index-FGZCz9p2.js:59:161
React Router caught the following error during render TypeError: s.series.creators is undefined
    a https://gestion-metadonnees.developpement2.insee.fr/assets/index-DSJrezYZ.js:1
    Kb https://gestion-metadonnees.developpement2.insee.fr/assets/index-FGZCz9p2.js:1008
    Kb https://gestion-metadonnees.developpement2.insee.fr/assets/index-FGZCz9p2.js:1008
    e3 https://gestion-metadonnees.developpement2.insee.fr/assets/index-FGZCz9p2.js:57
    hse https://gestion-metadonnees.developpement2.insee.fr/assets/index-FGZCz9p2.js:59
    fse https://gestion-metadonnees.developpement2.insee.fr/assets/index-FGZCz9p2.js:59
    TEe https://gestion-metadonnees.developpement2.insee.fr/assets/index-FGZCz9p2.js:59
    IC https://gestion-metadonnees.developpement2.insee.fr/assets/index-FGZCz9p2.js:59
    G$ https://gestion-metadonnees.developpement2.insee.fr/assets/index-FGZCz9p2.js:59
    use https://gestion-metadonnees.developpement2.insee.fr/assets/index-FGZCz9p2.js:59
    k https://gestion-metadonnees.developpement2.insee.fr/assets/index-FGZCz9p2.js:44
    G https://gestion-metadonnees.developpement2.insee.fr/assets/index-FGZCz9p2.js:44
 
Object { componentStack: "\nKb@https://gestion-metadonnees.developpement2.insee.fr/assets/index-FGZCz9p2.js:1008:39342\ndiv\nGc@https://gestion-metadonnees.developpement2.insee.fr/assets/index-FGZCz9p2.js:88:9832\nv@https://gestion-metadonnees.developpement2.insee.fr/assets/index-DSJrezYZ.js:1:885\ndiv\nF@https://gestion-metadonnees.developpement2.insee.fr/assets/index-DSJrezYZ.js:1:1444\nVCe@https://gestion-metadonnees.developpement2.insee.fr/assets/index-FGZCz9p2.js:79:3798\ntTe@https://gestion-metadonnees.developpement2.insee.fr/assets/index-FGZCz9p2.js:79:7823\nI@https://gestion-metadonnees.developpement2.insee.fr/assets/layout-YKwy7gUw.js:1:2179\nVCe@https://gestion-metadonnees.developpement2.insee.fr/assets/index-FGZCz9p2.js:79:3798\ntTe@https://gestion-metadonnees.developpement2.insee.fr/assets/index-FGZCz9p2.js:79:7823\ndiv\ng3t@https://gestion-metadonnees.developpement2.insee.fr/assets/index-FGZCz9p2.js:1011:83970\nGZe@https://gestion-metadonnees.developpement2.insee.fr/assets/index-FGZCz9p2.js:1008:8203\nN@https://gestion-metadonnees.developpement2.insee.fr/assets/index-FGZCz9p2.js:32:3684\nt@https://gestion-metadonnees.developpement2.insee.fr/assets/index-FGZCz9p2.js:1008:8827\nN@https://gestion-metadonnees.developpement2.insee.fr/assets/index-FGZCz9p2.js:32:3684\nVCe@https://gestion-metadonnees.developpement2.insee.fr/assets/index-FGZCz9p2.js:79:3798\nKCe@https://gestion-metadonnees.developpement2.insee.fr/assets/index-FGZCz9p2.js:79:3014\nSTe@https://gestion-metadonnees.developpement2.insee.fr/assets/index-FGZCz9p2.js:88:5231\nrTe@https://gestion-metadonnees.developpement2.insee.fr/assets/index-FGZCz9p2.js:79:7954\nyTe@https://gestion-metadonnees.developpement2.insee.fr/assets/index-FGZCz9p2.js:88:2443\nSuspense\n_rt@https://gestion-metadonnees.developpement2.insee.fr/assets/index-FGZCz9p2.js:1008:153730\nm3t\nmain\nJTe@https://gestion-metadonnees.developpement2.insee.fr/assets/index-FGZCz9p2.js:88:34275\nDwe@https://gestion-metadonnees.developpement2.insee.fr/assets/index-FGZCz9p2.js:18:2562\nnke@https://gestion-metadonnees.developpement2.insee.fr/assets/index-FGZCz9p2.js:854:91865\no@https://gestion-metadonnees.developpement2.insee.fr/assets/index-FGZCz9p2.js:1008:5183" }
index-FGZCz9p2.js:79:3467
TypeError: s.series.creators is undefined
    a https://gestion-metadonnees.developpement2.insee.fr/assets/index-DSJrezYZ.js:1
    Kb https://gestion-metadonnees.developpement2.insee.fr/assets/index-FGZCz9p2.js:1008
    Kb https://gestion-metadonnees.developpement2.insee.fr/assets/index-FGZCz9p2.js:1008
    e3 https://gestion-metadonnees.developpement2.insee.fr/assets/index-FGZCz9p2.js:57
    hse https://gestion-metadonnees.developpement2.insee.fr/assets/index-FGZCz9p2.js:59
    fse https://gestion-metadonnees.developpement2.insee.fr/assets/index-FGZCz9p2.js:59
    TEe https://gestion-metadonnees.developpement2.insee.fr/assets/index-FGZCz9p2.js:59
    IC https://gestion-metadonnees.developpement2.insee.fr/assets/index-FGZCz9p2.js:59
    G$ https://gestion-metadonnees.developpement2.insee.fr/assets/index-FGZCz9p2.js:59
    use https://gestion-metadonnees.developpement2.insee.fr/assets/index-FGZCz9p2.js:59
    k https://gestion-metadonnees.developpement2.insee.fr/assets/index-FGZCz9p2.js:44
    G https://gestion-metadonnees.developpement2.insee.fr/assets/index-FGZCz9p2.js:44
index-FGZCz9p2.js:59:161
React Router caught the following error during render TypeError: s.series.creators is undefined
    a https://gestion-metadonnees.developpement2.insee.fr/assets/index-DSJrezYZ.js:1
    Kb https://gestion-metadonnees.developpement2.insee.fr/assets/index-FGZCz9p2.js:1008
    Kb https://gestion-metadonnees.developpement2.insee.fr/assets/index-FGZCz9p2.js:1008
    e3 https://gestion-metadonnees.developpement2.insee.fr/assets/index-FGZCz9p2.js:57
    hse https://gestion-metadonnees.developpement2.insee.fr/assets/index-FGZCz9p2.js:59
    fse https://gestion-metadonnees.developpement2.insee.fr/assets/index-FGZCz9p2.js:59
    TEe https://gestion-metadonnees.developpement2.insee.fr/assets/index-FGZCz9p2.js:59
    IC https://gestion-metadonnees.developpement2.insee.fr/assets/index-FGZCz9p2.js:59
    G$ https://gestion-metadonnees.developpement2.insee.fr/assets/index-FGZCz9p2.js:59
    use https://gestion-metadonnees.developpement2.insee.fr/assets/index-FGZCz9p2.js:59
    k https://gestion-metadonnees.developpement2.insee.fr/assets/index-FGZCz9p2.js:44
    G https://gestion-metadonnees.developpement2.insee.fr/assets/index-FGZCz9p2.js:44
 
Object { componentStack: "\nKb@https://gestion-metadonnees.developpement2.insee.fr/assets/index-FGZCz9p2.js:1008:39342\ndiv\nGc@https://gestion-metadonnees.developpement2.insee.fr/assets/index-FGZCz9p2.js:88:9832\nv@https://gestion-metadonnees.developpement2.insee.fr/assets/index-DSJrezYZ.js:1:885\ndiv\nF@https://gestion-metadonnees.developpement2.insee.fr/assets/index-DSJrezYZ.js:1:1444\nVCe@https://gestion-metadonnees.developpement2.insee.fr/assets/index-FGZCz9p2.js:79:3798\ntTe@https://gestion-metadonnees.developpement2.insee.fr/assets/index-FGZCz9p2.js:79:7823\nI@https://gestion-metadonnees.developpement2.insee.fr/assets/layout-YKwy7gUw.js:1:2179\nVCe@https://gestion-metadonnees.developpement2.insee.fr/assets/index-FGZCz9p2.js:79:3798\ntTe@https://gestion-metadonnees.developpement2.insee.fr/assets/index-FGZCz9p2.js:79:7823\ndiv\ng3t@https://gestion-metadonnees.developpement2.insee.fr/assets/index-FGZCz9p2.js:1011:83970\nGZe@https://gestion-metadonnees.developpement2.insee.fr/assets/index-FGZCz9p2.js:1008:8203\nN@https://gestion-metadonnees.developpement2.insee.fr/assets/index-FGZCz9p2.js:32:3684\nt@https://gestion-metadonnees.developpement2.insee.fr/assets/index-FGZCz9p2.js:1008:8827\nN@https://gestion-metadonnees.developpement2.insee.fr/assets/index-FGZCz9p2.js:32:3684\nVCe@https://gestion-metadonnees.developpement2.insee.fr/assets/index-FGZCz9p2.js:79:3798\nKCe@https://gestion-metadonnees.developpement2.insee.fr/assets/index-FGZCz9p2.js:79:3014\nSTe@https://gestion-metadonnees.developpement2.insee.fr/assets/index-FGZCz9p2.js:88:5231\nrTe@https://gestion-metadonnees.developpement2.insee.fr/assets/index-FGZCz9p2.js:79:7954\nyTe@https://gestion-metadonnees.developpement2.insee.fr/assets/index-FGZCz9p2.js:88:2443\nSuspense\n_rt@https://gestion-metadonnees.developpement2.insee.fr/assets/index-FGZCz9p2.js:1008:153730\nm3t\nmain\nJTe@https://gestion-metadonnees.developpement2.insee.fr/assets/index-FGZCz9p2.js:88:34275\nDwe@https://gestion-metadonnees.developpement2.insee.fr/assets/index-FGZCz9p2.js:18:2562\nnke@https://gestion-metadonnees.developpement2.insee.fr/assets/index-FGZCz9p2.js:854:91865\no@https://gestion-metadonnees.developpement2.insee.fr/assets/index-FGZCz9p2.js:1008:5183" }
index-FGZCz9p2.js:79:3467

**Comment by CatherineGoillot** [comment]
Test : OK

Je suis tjrs gestionnaire et je n'ai plus de message d'erreur quand j'affiche une opération.
