### ISSUE TITLE
La fenêtre de confirmation se déclenche à la création des rapports

### ISSUE THREAD

**Issue by flo7894** [InseeFr/Bauhaus#1024]
Quel que soit le rôle quand on sélectionne un indicateur, une série ou une opération pour laquelle le rapport n'existe pas encore et qu'on crée un rapport à la sauvegarde du rapport la fenêtre d'alerte se déclenche à tord.

- je clique sur Créer un rapport. Je renseigne 1 rubrique
- je clique sur Sauvegarder (on voit un requête post avec un 200 passer). J'ai la pop-up suivante
 ![Image](https://github.com/user-attachments/assets/5d296319-6fc3-4fbf-8d9b-75b1a5fabb29)

**Comment by CatherineGoillot** [comment]
25/11 : 
Test sur dev : Ok
