### ISSUE TITLE
A la création d'une opération, on reste sur le formulaire

### ISSUE THREAD

**Issue by flo7894** [InseeFr/Bauhaus#1025]
Depuis le formulaire de création d'une opération "https://.../operations/operation/create", après avoir saisi les informations obligatoires, si on clique sur "Sauvegarder" la création se passe bien (on a un post 200 dans la log) mais on reste sur le formulaire de création au lieu de basculer sur "https://.../operations/operation/s*XXXX*"

**Comment by CatherineGoillot** [comment]
25/11 : 
test sur dev : OK
