### ISSUE TITLE
La fonction de copie des rapports ne fonctionne plus

### ISSUE THREAD

**Issue by flo7894** [InseeFr/Bauhaus#1027]
Depuis le formulaire de modification ou de création, lorsqu'on sélectionne un rapport existant pour en copier le contenu dans le formulaire l'application mouline sans discontinuer (mais on voit bien un get 200 passer pour récupérer les informations du rapport existant qu'on voulait copier)

![Image](https://github.com/user-attachments/assets/a6f49ad4-16c1-4974-8f2c-665758a11836)

![Image](https://github.com/user-attachments/assets/fcdcfc39-e00c-4b20-9d3a-549ce98ba912)

**Comment by CatherineGoillot** [comment]
25/11
Tests sur dev : Ok
