### ISSUE TITLE
Problème sur la home des concepts

### ISSUE THREAD

**Issue by EmmanuelDemey** [InseeFr/Bauhaus#1031]
- De temps en temps, après une recherche dans la home page des Concepts, la liste des concepts se vident... 

peut etre lié https://github.com/orgs/InseeFr/projects/9/views/8?pane=issue&itemId=83064451&issue=InseeFr%7CBauhaus%7C1019

**Comment by CatherineGoillot** [comment]
Tests : OK

Le retour à la home Concepts affiche bien tous les concepts saisis.
