### ISSUE TITLE
Vérifier la gestion du cache (index.html) pour le SSM (afin d'éviter de faire Ctrl F5 à chaque déploiement).

### ISSUE THREAD

**Issue by EmmanuelDemey** [InseeFr/Bauhaus#1064]

**Comment by CatherineGoillot** [comment]
Comment teste-t'on ce ticket ?
Merci

**Comment by EmmanuelDemey** [comment]
MEP 2/12 sur l'environnement SSM version 4.1.5

MEP 9/12  sur l'environnement SSM version > 4.1.5 => si tu fais un F5 sur l'application, si tu n'as pas d'erreurs, c'est que c'est BON.

**Comment by CatherineGoillot** [comment]
Test : OK
