### ISSUE TITLE
Erreur 500 à la création de structure ou de jeu de données

### ISSUE THREAD

**Issue by flo7894** [InseeFr/Bauhaus#1065]
Avec le rôle gestionnaire (de structures ou de jeux de donnée).
Depuis le formulaire de création d'une structure ou d'un jeu de données lorsqu'on sauvegarde après avoir rempli les champs obligatoires on a une erreur 500 de la part du back et le message suivant à l'ihm

Cannot construct instance of `java.util.ArrayList` (although at least one Creator exists): no String-argument constructor/factory method to deserialize from String value ('DG75-L201') at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 1, column: 232] (through reference chain: fr.insee.rmes.model.structures.Structure["contributor"])

Le problème semble venir du pré-remplissage du champ "gestionnaire", si on le "clear" et qu'on sélectionne le timbre, lors de la sauvegarde on a encore une erreur mais qui semble du fait du back, cf https://github.com/InseeFr/Bauhaus-Back-Office/issues/799

**Comment by flo7894** [comment]
@EmmanuelDemey 
Sur la création de structure et de composant avec le rôle gestionnaire on a maintenant une erreur 403 sur la back-office.
Cette erreur n'est par ailleurs pas intercepté par le front (on reste sur le formulaire de création sans message)

**Comment by CatherineGoillot** [comment]
Test : Ok

Plus d'erreur 500 mais une erreur 403 décrite dans le ticket https://github.com/orgs/InseeFr/projects/9/views/5?pane=issue&itemId=86516291&issue=InseeFr%7CBauhaus-Back-Office%7C799
