### ISSUE TITLE
Propriété millésime au niveau opération

### ISSUE THREAD

**Issue by EmmanuelDemey** [InseeFr/Bauhaus#1068]
Ajouter un champ de description de la période temporelle (du millésime) de l'opération . 
champ texte, pour caractériser et designer une opération avec une information relative à sa temporalité

**Comment by EmmanuelDemey** [comment]
@flo7894 @dzkwsk @ChristopheYon doivent définir le predicat.

**Comment by EmmanuelDemey** [comment]
Il faudra l'ajouter sur Magma également.

**Comment by EmmanuelDemey** [comment]
@PierreVasseur je viens de créer une PR pour l'ajout coté Back : https://github.com/InseeFr/Bauhaus-Back-Office/pull/813

**Comment by CatherineGoillot** [comment]
@EmmanuelDemey : le prédicat à utiliser est http://purl.org/dc/terms/temporal

**Comment by EmmanuelDemey** [comment]
merci @CatherineGoillot

**Comment by CatherineGoillot** [comment]
Test : KO
Il faudrait que le champ soit enregistré comme xsd:gYear au lieu de xsd:int

A la sauvegarde, avoir un message d'alerte pour signifier que le champ n'est pas conforme.
Actuellement il y a 2 pbs : 
- si on saisit une chaine de caractères, le champ n'est pas enregistré 
- si on saisit un nombre décimal, on a une erreur 500 de la part du back
