### ISSUE TITLE
Quand j'annule (retour) une collection à exporter, je reviens sur une page introuvable

### ISSUE THREAD

**Issue by PierreVasseur** [InseeFr/Bauhaus#1076]
Je clique sur Collections, puis sur Exporter.
- je clique sur Retour =>je reviens sur une page Introuvable.
- idem après la sélection d'une collection 
Même en rafraichissant, on reste toujours sur la page Introuvable.
Rien dans la console

**Comment by PierreVasseur** [comment]
Je ne reproduis pas le problème en dev2 ni en prod

**Comment by CatherineGoillot** [comment]
Test : OK
Je retourne bien sur la page des collections.
