### ISSUE TITLE
Etre capable de télécharger une liste de concepts

### ISSUE THREAD

**Issue by EmmanuelDemey** [InseeFr/Bauhaus#419]

**Comment by Emilia-Vittek** [comment]
cf issue #421

**Comment by EmmanuelDemey** [comment]
@Emilia-Vittek je viens de faire une nouvelle PR pour corriger les deux derniers bugs.

**Comment by Emilia-Vittek** [comment]
@EmmanuelDemey  Pour l'instant le bouton "Exporter" n'est pas branché sur la même version de développement que celui qui permet de télécharger une liste de collections (#421)

**Comment by EmmanuelDemey** [comment]
Pour moi le bouton apparait correctement avec le dropdown permettant de sélectionner le type de document souhaité. 
Je viens tout de même d'ajouter une PR avec l'ajout dun message si zero concepts ne sont sélectionnés. 

https://github.com/InseeFr/Bauhaus/pull/495/

**Comment by EmmanuelDemey** [comment]
@Emilia-Vittek en fait la PR du Back n'avait pas été mergée. Elle a été faite ce matin, et @JeromeMBourgeois va faire le déploiement. 

https://github.com/InseeFr/Bauhaus-Back-Office/pull/367

**Comment by Emilia-Vittek** [comment]
@EmmanuelDemey C'est nickel. Merci.
