### ISSUE TITLE
Etre capable de télécharger une liste de collections

### ISSUE THREAD

**Issue by EmmanuelDemey** [InseeFr/Bauhaus#421]

**Comment by Emilia-Vittek** [comment]
Quatre remarques sur ce développement :

1. Mettre un test pour vérifier que l'utilisateur a sélectionné au moins une collection avant de demander l'exportation et afficher un message si ce n'est pas le cas " Veuillez sélectionner au moins un objet à exporter "
2. Remplacer le libellé de l'item " Exporter les concepts membres de la collection " par " Exporter les fiches des concepts de la sélection " 
3. Le résultat de l'exportation en "ods" ne donne pas les mêmes informations selon qu'on exporte une liste de collections ou un ensemble de concepts.
4. Le résultat de l'exportation en "odt" (première ou seconde langue) ne donne pas les mêmes informations selon qu'on exporte une liste de collections ou un ensemble de concepts.

**Comment by EmmanuelDemey** [comment]
@Emilia-Vittek peux tu m'indiquer la différence que tu détectes lors de l'export ?

**Comment by EmmanuelDemey** [comment]
@JeromeMBourgeois je viens de faire une PR avec la correction des deux premiers points.

**Comment by Emilia-Vittek** [comment]
@EmmanuelDemey 
Rien ne fonctionne quand je veux tester, alors que toutes els tâches sont cochées. Est-ce trop tôt ?

**Comment by EmmanuelDemey** [comment]
@Emilia-Vittek La PR n'a toujours pas été relue ni mergé (donc pas déployée).

**Comment by Emilia-Vittek** [comment]
@EmmanuelDemey 
Ok. Merci.

**Comment by Emilia-Vittek** [comment]
@EmmanuelDemey Merci pour ces changements. Voici le retour de la recette pas à pas pour l'exportation des listes de collections : 

 - test pour vérifier que l'utilisateur a sélectonné au moins une collection ==> le bouton "Experter" est inactif tant qu'il n'y a pas de collection de sélectionnée, ce qui est très bien. MAIS, il n'y a pas de message pour prévenir l'utilisateur ==> est-il possible de le rajouter, stp ?
 - libellé validé ;
 - exportation en ods validée ;
 - exportations en odt validées.

**Comment by EmmanuelDemey** [comment]
Une nouvelle PR réalisée. https://github.com/InseeFr/Bauhaus/pull/494/

**Comment by Emilia-Vittek** [comment]
@EmmanuelDemey Les mêmes causes produisant les mêmes effets, c'est nickel aussi. Merci.
