### ISSUE TITLE
Revoir les composants permettant de selectionner un timbre lors de la creation et mise à jour d'une collection

### ISSUE THREAD

**Issue by EmmanuelDemey** [InseeFr/Bauhaus#425]
Afin de faire des optimisations sur l'application (eviter de faire trop de requetes sur des données qui changent peu), je commence à mettre en cache certaines choses. Notamment le choix d'un stamp (pour le créator d'une collection). 

Pour recette cette carte, il suffit de regarder si la creation et mise à jour d'une collection fonctionne toujours.

**Comment by EmmanuelDemey** [comment]
@Emilia-Vittek pour recette cette carte, il faut vérifier que quand on met a jour une collection, le champ de formulaire permettant de sélectionner un timbre fonctionne toujours.

**Comment by Emilia-Vittek** [comment]
@EmmanuelDemey  J'ai créé deux concepts, puis une collection qui reprend entre autres ces deux concepts. J'ai toujours une sélection obligatoire du timbre du propriétaire sur liste déroulante ==> OK
Je valide et passe en recette.

**Comment by EmmanuelDemey** [comment]
PR pour la prod https://github.com/InseeFr/Bauhaus/pull/485
