### ISSUE TITLE
Créer un composant specifique pour l'icone etoile rouge sur les formulaire

### ISSUE THREAD

**Issue by EmmanuelDemey** [InseeFr/Bauhaus#427]

**Comment by EmmanuelDemey** [comment]
@Emilia-Vittek pour recette cette carte, il suffit de vérifier que la petite etoile rouge qui indique qu'un champ de formulaire s'affiche toujours.

**Comment by Emilia-Vittek** [comment]
@EmmanuelDemey
**Validation Ok**, par test en voulant : 

- saisir ou modifier : 
   ==> un concept ou une collection ;
   ==> une famille, une série, une opération ou un indicateur ;
   ==> un composant ;
   ==> une liste de codes ou une liste de codes partielle ;
- saisir, dupliquer ou modifier : 
   ==> une structure ;
- modifier : 
   ==> une nomenclature.

**Comment by EmmanuelDemey** [comment]
https://github.com/InseeFr/Bauhaus/pull/462
