### ISSUE TITLE
Modification d'un lien ou d'un document - Message d'alerte

### ISSUE THREAD

**Issue by Emilia-Vittek** [InseeFr/Bauhaus#432]

**Comment by Emilia-Vittek** [comment]
L’utilisateur modifie un lien ou un document qui est déjà utilisé dans au moins un rapport (comme mentionné dans la partie “ Liens / Sims associés ”.

Dans ce cas, au moment où il clique sur “ sauvegarder ” il faut qu’il ait un message d’alerte disant “ Ce lien (ou ce document) est déjà utilisé dans les Sims suivants (mettre la liste). Si vous cliquez sur “ Oui ” il sera définitivement modifié dans tous les Sims associés. Voulez-vous continuer ? ” avec une possibilité de réponse “ Oui ” / “ Non ”

(Remplacer les boutons "Annuler" et "Sauvegarder" par "Non" et "Oui", dans le même ordre que dans Windows, si possible)

**Comment by EmmanuelDemey** [comment]
Cette fonctionnalité est déjà sur la branche main.
