### ISSUE TITLE
Résoudre le problème de création d'un document

### ISSUE THREAD

**Issue by EmmanuelDemey** [InseeFr/Bauhaus#457]

**Comment by Emilia-Vittek** [comment]
@EmmanuelDemey J'ai testé la création d'un document et la création d'un lien et je les ai utilisés dans un rapport  ==> c'est OK.
En revanche, j'ai un problème à l'exportation car cela me met un document qui n'est pas dans le rapport. Je crée une carte spécifique.

**Comment by EmmanuelDemey** [comment]
Étrange. Faudra voir avec @JeromeMBourgeois dans la base de qf une fois que la carte est créée.

**Comment by Emilia-Vittek** [comment]
@EmmanuelDemey

**Comment by EmmanuelDemey** [comment]
Oui tout a fait.

**Comment by EmmanuelDemey** [comment]
PR pour la prod https://github.com/InseeFr/Bauhaus/pull/474
