### ISSUE TITLE
Modification d'un lien ou d'un document - Possibilité de le faire

### ISSUE THREAD

**Issue by Emilia-Vittek** [InseeFr/Bauhaus#471]
Après avoir créé un document, si je veux changer le fichier qui est derrière, il refuse de le faire mais ne me préviens pas. Quand je clique sur le bouton "Sauvegarder", Bauhaus reviens juste à la page d'accueil du document sans aucun changement, ni message d'alerte.

**Comment by EmmanuelDemey** [comment]
@Emilia-Vittek afin de faciliter le débug, peux tu me donner le nom du fichier que tu upload la seconde fois ?
