### ISSUE TITLE
initialisation du module "jeux de données"

### ISSUE THREAD

**Issue by EmmanuelDemey** [InseeFr/Bauhaus#478]
- [x] Coté Front
- [x] InseeFr/Bauhaus-Back-Office#509

**Comment by EmmanuelDemey** [comment]
@flo7894 doit spécifier

**Comment by flo7894** [comment]
Pour l'onglet "Jeux de données" le formulaire de création aura les champs suivants :

- titre/title : string multilingue avec le prédicat <http://purl.org/dc/terms/title>
- description (fr)/ description (en) : string multilingue avec le prédicat <http://purl.org/dc/terms/description>
- propriétaire : choix multiple dans la liste des timbres avec le predicat <http://purl.org/dc/elements/1.1/creator>
- gestionnaire : choix multiple dans la liste des timbres avec le predicat <http://purl.org/dc/elements/1.1/contributor>
- date de création : date et heure (quelque chose comme pour les documents dans le module opérations, ce champ sera principalement mis à jour par les applications clientes du module lorsqu'il y aura un chargement de données dans leur système) avec le prédicat <http://purl.org/dc/terms/created>
- date de modification : date et heure (quelque chose comme pour les documents dans le module opérations, ce champ sera principalement mis à jour par les applications clientes du module lorsqu'il y aura un chargement de données dans leur système) avec le prédicat <http://purl.org/dc/terms/created>
- statut de diffusion : choix unique dans la liste des statuts avec le prédicat <http://rdf.insee.fr/def/base#disseminationStatus>
- produit par : choix unique dans la liste des séries et opérations avec le prédicat <http://www.w3.org/ns/prov#wasGeneratedBy>
- theme : choix multiple dans la liste des thèmes (ensemble des concepts du graphe en pj) avec la prédicat <http://www.w3.org/dcat#theme>

[themes.txt](https://github.com/InseeFr/Bauhaus/files/12583025/themes.txt)

**Comment by flo7894** [comment]
Pour l'onglet "Distribution" le formulaire de création aura les champs suivants :

- jeu de données : choix unique dans la liste de jeux de données
- titre/title : string multilingue avec le prédicat <http://purl.org/dc/terms/title>
- description (fr)/ description (en) : string multilingue avec le prédicat <http://purl.org/dc/terms/description>
- date de création : date et heure (quelque chose comme pour les documents dans le module opérations, ce champ sera principalement mis à jour par les applications clientes du module lorsqu'il y aura un chargement de données dans leur système) avec le prédicat <http://purl.org/dc/terms/created>
- date de modification : date et heure (quelque chose comme pour les documents dans le module opérations, ce champ sera principalement mis à jour par les applications clientes du module lorsqu'il y aura un chargement de données dans leur système) avec le prédicat <http://purl.org/dc/terms/created>
- format : choix unique dans la liste suivante "CSV", "PARQUET" avec le predicat <http://purl.org/dc/terms/format>
- taille : un entier avec le prédicat <http://www.w3.org/dcat#byteSize>
- url de téléchargement : une url avec le predicat <http://www.w3.org/dcat#downloadURL>

**Comment by flo7894** [comment]
A la création d'un jeux de données les champs titre, propriétaire, gestionnaire et statut de diffusion sont obligatoires

A la création d'une distribution seule la sélection du jeux de données "parent" est obligatoire

**Comment by flo7894** [comment]
Sur la page d'accueil de l'onglet "jeux de données" la recherche se fait sur le titre du jeux de données

Sur la page d'accueil de l'onglet "distribution" la recherche se faire sur "titre du jeux de donnnées" + "titre de la distribution"

**Comment by flo7894** [comment]
Pour la visualisation du détail d'une distribution dans l'onglet information générales on affichera les champs
- identifiant (dcterms:identifier , généré automatiquement à la création)
- date de création (dcterms:created, si renseignée)
- date de modification (dcterms:modified, si renseignée)
- état de la distribution (insee:validationState, généré à "Unpublished" à la création)

**Comment by EmmanuelDemey** [comment]
@flo7894 les propriétés url et taille sont des informations que l'utilisateurs doit entrer manuellement ? Ou des données que le back doit remplir automatiquement en fonction d'autres informations ?

**Comment by flo7894** [comment]
@EmmanuelDemey les propriétés url et taille d'une distribution doivent pouvoir être entrées manuellement, même si dans la majorité des cas on espère qu'elles seront plutôt poussées par des systèmes partenaires.

**Comment by EmmanuelDemey** [comment]
@flo7894 très clair.

**Comment by EmmanuelDemey** [comment]
```
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX dcterms: <http://purl.org/dc/terms/>

PREFIX dct: <http://purl.org/dc/terms/>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX insee: <http://rdf.insee.fr/def/base#>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX dcat: <http://www.w3.org/ns/dcat#>

SELECT ?id ?label ?labelDataset
FROM <http://rdf.insee.fr/graphes/catalogues> 
WHERE {
    ?uriDataset rdf:type <http://www.w3.org/dcat#Dataset> .
    ?uriDataset <http://www.w3.org/dcat#distribution> ?uri .
    
    ?uri rdf:type <http://www.w3.org/dcat#Distribution> .
	?uri dcterms:title ?label
    FILTER (lang(?label) = 'fr') .
	
	?uriDataset dcterms:title ?labelDataset
    FILTER (lang(?labelDataset) = 'fr') .

	BIND(STRAFTER(STR(?uri),'/catalogues/distribution/') AS ?id) .
}
```

**Comment by EmmanuelDemey** [comment]
https://github.com/InseeFr/Bauhaus/pull/498
https://github.com/InseeFr/Bauhaus-Back-Office/pulls

**Comment by EmmanuelDemey** [comment]
@flo7894 n'oublie pas de mentionner à l'ecrit les subtilités concernant la récupération des thèmes discutés vendredi.

**Comment by flo7894** [comment]
Un jeu de données peut avoir plusieurs thèmes et ces thèmes peuvent de la même ou de différentes listes de thèmes (appelées ThemeTaxonomy dans le vocabulaire dcat)

Les échanges avec les unités responsables de la diffusion des données ont conduit à retenir deux listes de thèmes. Elles sont gérées comme des conceptScheme et sont dans le graphe http://rdf.insee.fr/graphes/concepts . 
Les identifiants de ces listes de thèmes sont "inseeTheme" et "classificationOfStatisticalDomain", les triplets correspondants ont la forme
\<uriListeDeTheme\> skos:notation \<identifiantListeDeTheme\>
Les thèmes sont liés à une liste via des triplets de la forme \<uriTheme\> skos:inScheme \<uriListeDeTheme\>

**Comment by flo7894** [comment]
Quelques coquilles de langue à l'affichage :

- Quand on est sur l'écran de visualisation du détail d'un jeu de données avec l'option seconde langue, le libellé langue 1 est affiché deux fois
- Quand on est sur l'écran de visualisation du détail d'un jeu de données on a le libellé anglais du thème dans l'affichage, il faudrait le libellé de la langue 1
- Quand on sélectionne un thème on a les libellés dans les deux langues qui sont visibles, il faudrait seulement celui de la langue 1
- Quand on est sur l'écran de visualisation du détail d'un jeu de données avec l'option seconde langue, le libellé langue 1 est affiché deux fois 

Et il faudrait modifier "Produit de" / "Produced from" par "Produit par" / "Was generated by". Je préfèrerai réserver le "de" si on se décide à modéliser le lignage/dérivation entre jeux de données

**Comment by EmmanuelDemey** [comment]
Je viens de faire les modifications.

**Comment by flo7894** [comment]
A la création d'un jeu de données, les champs indiqués comme obligatoires avec le "*" sont intitulés, titre, propriétaire et gestionnaire.

Si on ne saisit que ces quatre champs, la sauvegarde de fonctionne pas. La page reste en modification, affiche "Vous avez des erreurs dans ce formulaire." et le bouton sauvegarde devient grisé. A partir de cet état, même si on renseigne l'ensemble des champs il n'est plus possible de sauvegarder, le bouton reste indisponible avec le pointeur de la souris qui devient un panneau interdit au survol du bouton. Il faudrait qu'on puisse sauvegarder après avoir rempli les champs obligatoires.

A priori les champs "produit de" et "statut de diffusion" sont également obligatoire pour sauvegarder. Il faudrait mettre le "*" devant "statut de diffusion". il ne faudrait pas que "produit de" soit obligatoire.

**Comment by EmmanuelDemey** [comment]
Et il faudrait modifier "Produit de" / "Produced from" par "Produit par" / "Was generated by". Je préfèrerai réserver le "de" si on se décide à modéliser le lignage/dérivation entre jeux de données => Supprimer tous les "Produit de" / "Produced from"

**Comment by EmmanuelDemey** [comment]
@flo7894 n'oublie pas de définir les choses à modifier concernant les themes.

**Comment by EmmanuelDemey** [comment]
@flo7894  pour info, je viens de proposer une nouvelle PR avec les corrections demandées ci-dessus.
