### ISSUE TITLE
étude d'impact (enlever l'arbre de liste de codes)

### ISSUE THREAD

**Issue by EmmanuelDemey** [InseeFr/Bauhaus#483]

**Comment by EmmanuelDemey** [comment]
@flo7894 n'oublie pas d'ajouter la description de la nouvelle interface que tu souhaites.

**Comment by flo7894** [comment]
Dans l'onglet "listes de codes" qui serait renommer "Concept Schemes", on ne gererait plus la notion d'ordonnancement des codes au sein de la liste.
A l'affichage on conserverait le tableau "éléments" et on enlèverait la partie "arborescence"
En modification on aurait le tableau "éléments" à la place de "arborescence".
On aurait un fonctionnement similaire à ce qu'on a le formulaire de création d'une dsd. Il faudrait deux boutons pour chaque ligne du tableau un "engrenage" pour ouvrir une fenêtre de saisie pour modifier le code, un "-" pour supprimer le code de la liste
Il faudrait également un bouton "+" dans le bandeau "elements" pour ajouter un code. Ca déclencherait l'ouverture de la même fenêtre de saisie que pour la modification du code.
Il faudrait également ajouter un "rechercher dans le tableau" pouvoir filtrer les codes de façon à vérifier sur les grandes listes que le code que l'on pourrait vouloir ajouter n'existe pas déjà

![Image](https://github.com/InseeFr/Bauhaus/assets/41472504/bafd0745-b964-4f7a-b483-ec8df6635a48)



![Image](https://github.com/InseeFr/Bauhaus/assets/41472504/61bdaddd-b70c-420a-b51f-ab383da0f77c)



![Image](https://github.com/InseeFr/Bauhaus/assets/41472504/d693a509-ec5a-4d3e-9820-ac90b0fc7999)

**Comment by EmmanuelDemey** [comment]
Que pour les listes de codes totales. 

je peux supprimer tous les rdf_1, rdf_2, ...

**Comment by flo7894** [comment]
@EmmanuelDemey 

Lorsqu'on crée une liste, on ne peut pas créer de codes tant qu'on a pas sauvegardé la liste une première fois. 

```
XHRPOST
https://gestion-metadonnees-api.developpement2.insee.fr/codeList/detailed/CL_TEST_SAVE/codes
[HTTP/1.1 500  122ms]

Blocage d’une requête multiorigines (Cross-Origin Request) : la politique « Same Origin » ne permet pas de consulter la ressource distante située sur https://gestion-metadonnees-api.developpement2.insee.fr/codeList/detailed/CL_TEST_SAVE/codes. Raison : l’en-tête CORS « Access-Control-Allow-Origin » est manquant. Code d’état : 500.

Uncaught (in promise) TypeError: NetworkError when attempting to fetch resource. 
```

Peut-on dans ce cas masquer le tableau des codes sur le formulaire de création et ne le laisser apparaître que sur le formulaire de modification

**Comment by EmmanuelDemey** [comment]
Yes. Je viens de déplacer la carte.

**Comment by EmmanuelDemey** [comment]
PR https://github.com/InseeFr/Bauhaus/pull/532/
