### ISSUE TITLE
Gérer la longueur du nom du ZIP lors de l'export d'un SIMS

### ISSUE THREAD

**Issue by EmmanuelDemey** [InseeFr/Bauhaus#503]

**Comment by EmmanuelDemey** [comment]
https://github.com/InseeFr/Bauhaus/pull/504

**Comment by EmmanuelDemey** [comment]
https://github.com/InseeFr/Bauhaus-Back-Office/pull/423

**Comment by Emilia-Vittek** [comment]
1. Historique de la demande : cette carte fait suite à la carte sur la longueur des noms de fichiers à l'exportation #358 (actuellement, au 8 décembre 2023, dans la colonne "Fait en QF") où la demande de ramener les noms de fichier à 200 caractères à l'exportation pour un concept, une liste de concepts, une collection, 1 liste de collections et un rapport avec ses documents est validée pour le concept, la liste de concets, la collection et la liste de collections.
Il reste une question sur l'exportation du rapport, notamment quan il y a un zip parce que le rapport a des documents complémentaires.


2. Recette de la carte #503, ce vendredi 8 décembre 2023 :
 2.1 Création du rapport d'une série dont le nom fait plus de 200 caractères (à savoir 229 pour le test, avec le nom suivant : FichierAMettreDansUnRapportPourTesterLaRegleSurLaLongueurDesNomsDeFichierAfinDeVoirSiCestBienTronqueADeuxCentsCaracteresDansLExportationDuRapportDansLequelIlYEstFaitReferenceCommeDocumentLieQuiVientCompleterLesInformationsSaisies) ==> le nom du fichier à l'exportation fait plus de 200 caractères (ou 204 selon la façon de compter l'extension). Il se décompose en 16 caractères pour le préfixe "Rapport qualité" + 204 caractères pour le nom du rapport + 4 caractères pour l'extension .odt, soit au total 224 caractères  ==> problème ;

 2.2 Ajout d'un document dans ce rapport et exportation de l'ensemble
==> 1) le nom du fichier zip fait 207 caractères : pourquoi ? problème.
        2) le nom du dossier à l'intérieur du zip, qui comprend le rapport lui même et le document qui va avec fait 200 caractères : Ok
        3) le nom du fichier du rapport proprement dit fait 204 caractères : Ok.

Outre les questions de longueurs différentes et pas toujours en accord avec la demande, je constate dans ce test que :
  - la longueur du fichier du rapport n'est pas toujours la même suivant le chemin employé pour l'exporter (224 caractères quand il n'y a pas de document et 204 caractères quand il y a un document), ce qui laisse supposer que ce n'est pas le même programme qui s'exécute les deux fois ;
  - dans l'exportation avec un document, il reste des caractères diacritiques (en l'occurrence le signe ":") dans le nom du dossier et dans le nom du fichier du rapport, ce qui laisse supposer que là aussi tout n'est pas traité de la même façon (puisque par ailleurs je suis en train de recetter la carte "Supprimer le caractère diacritique sur les noms de fichiers #388" et que pour l'instant tous mes tests sont valides).

@EmmanuelDemey n'hésite pas à me solliciter si tout n'est pas clair.

Bonne réception, avec tous mes remerciements.

**Comment by EmmanuelDemey** [comment]
@Emilia-Vittek je viens de corrger le problème de la taille. 
Pour le 2e pb (diacritique), je conseille de créer une 2e carte car cela va etre compliqué de gérer proprement car, comme tu l'as indiqué, la modification a été apportée sur deux PR différentes, qui sont toutes les deux en phase de recette en parallèle.

**Comment by EmmanuelDemey** [comment]
https://github.com/InseeFr/Bauhaus-Back-Office/pull/462

**Comment by Emilia-Vittek** [comment]
@EmmanuelDemey Merci Manu. Je recette lorsque cela aura suivi son chemin et je crée la nouvelle carte sur le caractère diacritique, mais nous ne la rendons prioritaire que lorsque j'aurai recetté la modification actuelle correspondant à la carte "Supprimer le caractère diacritique sur les noms de fichiers https://github.com/InseeFr/Bauhaus/pull/388"

**Comment by Emilia-Vittek** [comment]
@EmmanuelDemey carte créée et décrite les 13 et 14 décembre 2023, actuellement classée dans "A spécifier" pour des raisons de gestion de flux.

**Comment by Emilia-Vittek** [comment]
Il s'agit de la carte "Gestion des caractères diacritiques dans l'exportation des rapports SIMS du fait de la mention "Rapport qualité" et du nom de la série"

**Comment by EmmanuelDemey** [comment]
@Emilia-Vittek j'ai recu la gestion des noms pour le téléchargement des SIMS. Car il y avait des traitements coté front et coté back. J'ai uniformisé pour que cela ne soit fait que coté back. 

PR à revoir pour @JeromeMBourgeois ou @FBibonne https://github.com/InseeFr/Bauhaus-Back-Office/pull/469/
PR à revoir pour @PierreVasseur https://github.com/InseeFr/Bauhaus/pull/546/files

**Comment by EmmanuelDemey** [comment]
@Emilia-Vittek doit compléter car il y a des disfonctionnment pour les rapports.

**Comment by Emilia-Vittek** [comment]
@EmmanuelDemey Je viens de boucler la recette et par conséquent : 

- c'est Ok pour l'exportation d'un concept, d'une liste de concepts, d'une collection et d'une liste de collections;
- il reste deux points à traiter pour les exportations de rapport, que cela soit un rapport de Série ou d'Opération ou d'Indicateur : 
                   * _exportation d'un rapport sans fichier joint_ ==> le nom du fichier à l'exportation (sans extension) est tronqué à 198 caractères au lieu de 200 ;
                   * _exportation d'un rapport avec au moins un document référencé_ ==>  le nom du fichier compressé (.zip) à l'exportation (sans extension) est tronqué à 198 caractères au lieu de 200.

Est-il possible de corriger, stp ? Cela permettra un traitement homogène dans tous les cas.
Merci.

**Comment by EmmanuelDemey** [comment]
Merci @Emilia-Vittek c'est très clair.

**Comment by EmmanuelDemey** [comment]
Mettre en production le PR. et créer un ticket sur le dernier problème rencontré.

**Comment by CatherineGoillot** [comment]
Tests : OK

- reste pb sur ":" à l'export sur un rapport qualité avec document. => ticket créé n° #101

**Comment by PierreVasseur** [comment]
le ticket créé est celui-ci : https://github.com/InseeFr/Bauhaus-Back-Office/issues/784 (Bauhaus Back Office et pas Bauhaus ;))
