### ISSUE TITLE
Compléter l'onglet "Informations statistiques" pour la saisie des jeux de données

### ISSUE THREAD

**Issue by EmmanuelDemey** [InseeFr/Bauhaus#515]
Il faudrait ajouter les champs de saisie suivants :

- Unités statistiques / Statistical Units : 
  - sélection multiple dans la liste de codes utilisés également par le module opération
  - enregistrement sous forme \<uriJeuDeDonnees\> \<http://rdf.insee.fr/def/base#statisticalUnit\> \<uriUniteStat\>)
- Structure de données/ Data structure :
  - sélection dans la liste des structures du module Bauhaus + possibilité d'écrire une chaîne de caractère
  - enregistrement sous forme \<uriJeuDeDonnees\> \<http://rdf.insee.fr/def/base#structure\> \<uriDsd\> ou String)
- Période temporelle couverte / Temporal coverage
  - saisie de deux dates 
- Résolution temporelle / Temporal resolution
  - sélection dans la liste de codes utilisés également par le module opération pour la fréquence
- Zone géographique couverte / Spatial coverage
  - sélection dans une liste de codes ou dans les territoires géo comme c'est fait pour le SIMS
- Résolution géographique / Spatial resolution
  - sélection multiple dans une liste de code 
- Nombre d'observations / Number of observation
  - saisie d'un entier
- Nombre de séries temporelles / Number of time-series
  - saisie d'un entier   

Dans cet onglet, il faudrait aussi un champ permettant des sélectionner une modalité de la liste CL_DATA_TYPES
Le triplet à enregistrer serait <uriDataset> dcterms:type <uriCodeTypeDonnees>;

**Comment by flo7894** [comment]
Les listes de codes pour le jeux de données

[listes-de-codes-pour-jeuxDeDonnees.zip](https://github.com/InseeFr/Bauhaus/files/13447215/listes-de-codes-pour-jeuxDeDonnees.zip)

**Comment by flo7894** [comment]
Pour Période temporelle couverte / Temporal coverage utiliser le prédicat dcterms:temporal 

l'objet est un noeud blanc qui prend les deux dates saisies [ dcat:startDate "1943" ; dcat:endDate "2020" ], comme on s'attend plutôt à saisir des années, il ne serait pas préférable de mettre un string pour les champ de saisies

Pour Nombre d'observations / Number of observation utiliser le prédicat insee:numObservations

Nombre de séries temporelles / Number of time-series utiliser le prédicat <http://data.europa.eu/m8g/numSeries>

**Comment by EmmanuelDemey** [comment]
@flo7894 j'ai plusieurs questions : 

- quelle est la structure de l'URI pour l'objet DCTERMS:TEMPORAL ?
- es tu sur de temporalResolution ? Car je ne l'ai pas dans rd4j (notre librairie java pour les requetes sparql)
- je ne comprends pas "comme on s'attend plutôt à saisir des années, il ne serait pas préférable de mettre un string pour les champ de saisies" :D
- C'est normal d'avoir le meme prédicat pour la Zone Géographique et la résolution géographique ?

**Comment by EmmanuelDemey** [comment]
merci @flo7894

**Comment by flo7894** [comment]
@EmmanuelDemey bon finalement sur la propriété dcterms:temporal, il y a quand même un besoin de saisir des dates et pas seulement des années. Est-ce qu'on peut donc faire une première sélection dans une liste "année" / "date" et en fonction du choix on a soit une sélection de deux années, soit une sélection de deux dates.
Et du coup dans le cas des dates stocker uriDataset  dcterms:temporal [ a dcterms:PeriodOfTime ; dcat:startDate "2022-01-01"^^xsd:date ; dcat:endDate "2023-01-01"^^xsd:date ; ]

**Comment by EmmanuelDemey** [comment]
@flo7894 comment fais tu pour sauvegarder si c'est une année où un date qui a été sélectionné en base de donnée ? Quel prédicat utilises tu ?

**Comment by EmmanuelDemey** [comment]
https://github.com/InseeFr/Bauhaus-Back-Office/pull/476
