### ISSUE TITLE
Mettre le champ thème en sélection multiple

### ISSUE THREAD

**Issue by EmmanuelDemey** [InseeFr/Bauhaus#516]
Dans le module catalogue, le champ thème ne permet pas actuellement de sélectionner plusieurs thèmes. 

Les thèmes pouvant provenir de deux listes, est qu'on pourrait afficher en plus du libellé du thème l'indentifiant du conceptScheme auquel il appartient. 

Quelque chose qui ressemblerait à ça (où n'importe quelle autre option qui permet de bien visualiser l'information)

![Image](https://github.com/InseeFr/Bauhaus/assets/41472504/82594db7-ab10-4a1a-8f35-ae48970df690)

Pour récupérer l'identifiant depuis le thème on peut suivre les triplets suivant :
\<uriTheme\> skos:inScheme \<uriConceptScheme\>
\<uriConceptScheme\> skos;notation "identifiantDuConceptScheme"

Et du coup il faudrait mettre "Thèmes" au lieu de "Thème" dans le formulaire

**Comment by flo7894** [comment]
Les triplets correspondants pour chaque liste de thèmes

[inseeTheme.txt](https://github.com/InseeFr/Bauhaus/files/13392287/inseeTheme.txt)

[statisticalDomain.txt](https://github.com/InseeFr/Bauhaus/files/13392289/statisticalDomain.txt)

**Comment by EmmanuelDemey** [comment]
PR pour le front = https://github.com/InseeFr/Bauhaus/pull/519/
