### ISSUE TITLE
Indication de champs obligatoires dans la saisie  de créations - deux formulaires (avant inventaire global)

### ISSUE THREAD

**Issue by Emilia-Vittek** [InseeFr/Bauhaus#523]
Les formulaires de saisie voient la mention "champ obligatoire" matérialisée par un astérique rouge.
Cet astérique manque : 
 - lors de la création d'une série, pour le champ "Famille" ;
 - lors de la création d'une opération, pour le champ "Série".
Est-il possible, svp,  de les rajouter ? Merci.

**Comment by PierreVasseur** [comment]
Problème résolu dans la PR [#735](https://github.com/InseeFr/Bauhaus/pull/735)
J'ai également rajouté un astérisque pour le fichier lors de la création d'un document
