### ISSUE TITLE
Compléter l'onglet "Informations générales" pour la saisie des jeux de données

### ISSUE THREAD

**Issue by flo7894** [InseeFr/Bauhaus#530]
Par rapport à l'existant il manque :sous-titre, première date de diffusion, fréquence de mise à jour, Droits d'accès, Statut de confidentialité, Organisme responsable de la publication des données, Page de présentation

L'onglet "informations générales" aurait les champs suivants à la cible :

|  |  |  |
| --- | --- | --- |
| Titre / Title  | champ texte multilingue | dcterms:title |
| Sous-titre / Sub-title | champ texte multilingue | insee:subtitle |
| Date de première diffusion des données | date | dcterms:issued |
| Date de dernière modification des données | date | dcterms:modified |
| Fréquence des mises à jour | sélection dans CL_FREQ| dcterms:accrualPeriodicity |
| Droits d'accès | sélection dans CL_ACCESS_RIGHTS| dcterms:accessRights |
| Statut de confidentialité | sélection dans CL_CONF_STATUS | insee:confidentialityStatus |
| Organisme responsable de la fourniture des données | sélection dans la liste des organismes | dcterms:creator |
| Organisme responsable de la publication des données | sélection dans la liste des organismes | dcterms:publisher |
| Produit par | liste des séries et opérations | prov:wasGeneratedBy |
| Thèmes | sélection multiple dans la liste des thèmes | dcat:theme |
| Page de présentation | champ de saisie pour une url pour chaque langue  | dcat:landingPage |

A la sauvegarde, seul le champ "titre" est obligatoire.

**Comment by EmmanuelDemey** [comment]
https://github.com/InseeFr/Bauhaus-Back-Office/pull/476
