### ISSUE TITLE
Mise en cohérence des nommages dans Bauhaus

### ISSUE THREAD

**Issue by EmmanuelDemey** [InseeFr/Bauhaus#627]
Diverses navigations dans Bauhaus montrent qu'il y a besoin d'une homogénéisation de certains noms de modules ou boutons,ou noms d'onglets et titres de page, svp :

- [x] Le module "jeu de données" est au singulier, contraiement aux autres ==> mettre "Jeux de données", avec un "x" à "jeu".

Le bouton de création, s'appelle "Nouveau" ou "Nouvelle" selon les cas, sans que cela soit accordé avec le genre de l'objet que l'on crée ==> les accorder tous. Concrètement cela veut dire que : 

- [x] module "Concepts" : "+ Nouveau" pour les concepts  et "+ Nouvelle" pour les collections ==> c'est Ok déjà ;
- [x] module "Nomenclatures" : pas de bouton de création ==> rien à faire ;
- [x] module "Opérations" : "+Nouvelle" pour les familles, "+ Nouvelle" pour les séries, "+ Nouvelle" pour les opérations et "+ Nouveau" pour les indicateurs ==> changer familles, séries et opérations ;
- [x] module "Structures" :  "+ Nouvelle" pour les structures et "+ Nouveau" pour les composants ==> C'est Ok déjà ;
- [x] module "Listes de codes" : "+ Nouvelle" pour les listes de codes et "+ Nouvelles" pour les listes de codes partielles ==> changer les listes de codes et les listes de codes partielles ;
- [x] module "Jeux de données" : "+ Nouveau" pour les jeux de données et "+ Nouvelle" pour les distributions ==> changer jeux de données.

pour les noms d'onglet ou titres de pages : 
module "Structures":

- [x]  dans l'onglet "Structures", remplacer le titre de la page "Data structure definition - Recherche" par "Structures - Recherche" ;
- [x]  dans l'onglet "Composants", remplacer le titre de la page "Composants" par "Composants - Recherche" ;

module "Listes de codes":

- [x] dans l'onglet "Listes de codes", remplacer le titre de la page "Liste de codes" par "Listes de codes - Recherche" ;
- [x] dans l'onglet "Listes de codes partielles", remplacer le titre de la page "Liste de codes" par "Listes de codes partielles - Recherche" ;
 
module "Jeux de données":
- [x] au niveau des onglets, remplacer le nom de l'onglet "Jeu de données" par "Jeux de données" ;
- [x] dans l'onglet "Jeux de données", remplacer le titre de la page "Jeu de données" par "Jeux de données - Recherche" ;
- [x] dans l'onglet "Distributions", remplacer le titre de la page "Distributions" par "Distributions - Recherche" ;

**Comment by Emilia-Vittek** [comment]
@EmmanuelDemey  Ok pour presque toutes les modifs.
Il me manque, stp : 

- le module "jeu de données" est au singulier, contrairement aux autres ==> mettre "Jeux de données", avec un "x" à "jeu".
- module jeux de données : 
      => au niveau des onglets, remplacer le nom de l'onglet "Jeu de données" par "Jeux de données" ;
      => au niveau des onglets, remplacer le nom de l'onglet "Distribution" par "Distributions". Je me permets de te rajouter ce dernier que je n'avais pas vu.

Merci bien.

**Comment by EmmanuelDemey** [comment]
Nouvelle PR . @PierreVasseur 
https://github.com/InseeFr/Bauhaus/pull/675

**Comment by Emilia-Vittek** [comment]
@EmmanuelDemey Parfait. Tout est OK. Merci.
