### ISSUE TITLE
Depuis la page de détail d'un jeu de données le bouton modifier ne fonctionne pas

### ISSUE THREAD

**Issue by flo7894** [InseeFr/Bauhaus#672]
Après création et sauvegarde d'un dataset depuis l'IHM, l'url affiché dans le navigateur indique "https://gestion-metadonnees.developpement2.insee.fr/datasets/jd1000" 
En revanche le bouton modifier indique qu'il appelle "https://gestion-metadonnees.developpement2.insee.fr/datasets//modify"

**Comment by EmmanuelDemey** [comment]
C'est étrange. je ne reproduis pas le problème... Peux tu m'indiquer la réponse HTTP reçu suite à la création du dataset @flo7894  ?

**Comment by EmmanuelDemey** [comment]
ping @flo7894  :D
