### ISSUE TITLE
Rafraîchissement de la liste des datasets après création

### ISSUE THREAD

**Issue by flo7894** [InseeFr/Bauhaus#673]
Après avoir sauvegarder un nouveau dataset et être revenu à l'onglet qui liste les datasets, le nouveau dataset n'apparaît.
Il apparaît avoir réactualisation manuelle de la page.

**Comment by EmmanuelDemey** [comment]
@flo7894 je pense que tu auras le même problèmes pour les distributions. Je vous ce que c'est. Je vais faire la modification

**Comment by EmmanuelDemey** [comment]
Nouvelle PR @PierreVasseur https://github.com/InseeFr/Bauhaus/pull/677
