### ISSUE TITLE
Le back ne va plus accepter les url qui se terminent par un / => 404

### ISSUE THREAD

**Issue by FBibonne** [InseeFr/Bauhaus#689]
Avec la montée de version à spring boot 3, spring ne mappe plus automatiquement les requêtes qui se terminent par un `/` 

Par exemple `GET https://gestion-metadonnees-api.developpement.insee.fr/organizations/` donnera lieu à une 404 alors que  `GET https://gestion-metadonnees-api.developpement.insee.fr/organizations` sera correctement traité (par le mapping déclaré en tant que `@RequestMapping("/organizations")`). L'explication côté spring boot est là : https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Migration-Guide#spring-mvc-and-webflux-url-matching-changes

Donc le front ne doit plus ajouter de / à la fin de ses requêtes.

Provisoirement le temps de la migration, la solution de contournement sera mise en place sur le back pour ne pas rejeter les requêtes en question

**Comment by EmmanuelDemey** [comment]
Préviens nous quand le back est prêt @FBibonne

**Comment by FBibonne** [comment]
Ok. dès que la PR 539 sera mergée sur le back

**Comment by FBibonne** [comment]
@EmmanuelDemey c'est prêt !
