### ISSUE TITLE
Filtrer le tableau des modalités d'une liste de codes

### ISSUE THREAD

**Issue by flo7894** [InseeFr/Bauhaus#749]
Il faudrait un champ qui permette de rechercher sur les codes, et un champ qui permette de rechercher sur les libellés.

On n'a pas besoin d'un filtrage dynamique si c'est coûteux en temps. Quand on valide l'un des champs de recherche on repasserait sur la page 1 du tableau

**Comment by EmmanuelDemey** [comment]
Je viens d'implémenter l'API pour cette carte. 

L'API sera de cette forme : 

/api/codeList/detailed/CL_CPE_APPART_SECTEUR/codes?page=1&search=labelLg1:pri&search=code:PR
/api/codeList/detailed/CL_CPE_APPART_SECTEUR/codes?page=1&search=labelLg1:pri
/api/codeList/detailed/CL_CPE_APPART_SECTEUR/codes?page=1&search=code:PR
/api/codeList/detailed/CL_CPE_APPART_SECTEUR/codes?page=1

Nous pouvons donc ne pas filtrer, filter sur 1 ou 2 champs.

**Comment by EmmanuelDemey** [comment]
https://github.com/InseeFr/Bauhaus-Back-Office/issues/586
