### ISSUE TITLE
Modification sur la création/modification de document

### ISSUE THREAD

**Issue by flo7894** [InseeFr/Bauhaus#909]
- [x] afficher un message d'erreur à l'utilisateur lorsqu'il essaye d'enregistrer avec un libellé lg1, un libellé lg2 ou un fichier identique à un document déjà existant
- [x] lorsqu'on soumet un fichier avec un nom non valide, le champ affiche un message d'erreur et le bouton sauvegarder se grise. à partir de là si l'on soumet un bon document le message d'erreur disparaît mais le bouton sauvegarder reste grisé

**Comment by Emilia-Vittek** [comment]
@PierreVasseur @flo7894 En ce qui concerne la soumission d'un fichier dont le nom est non valide, c'est probablement lié avec la carte de non rafraichissement des messages d'erreur et non réactivation du bouton sauvegarder #932

**Comment by CatherineGoillot** [comment]
Test : KO

- lorsqu'on soumet un fichier avec un nom non valide, le champ affiche un message d'erreur et le bouton sauvegarder se grise : OK
- à partir de là si l'on soumet un bon document le message d'erreur ne disparaît pas et le bouton sauvegarder redevient actif : OK

- afficher un message d'erreur à l'utilisateur lorsqu'il essaye d'enregistrer avec un libellé lg1 : OK
- afficher un message d'erreur à l'utilisateur lorsqu'il essaye d'enregistrer un libellé lg2 : OK

- afficher un message d'erreur à l'utilisateur lorsqu'il essaye d'enregistrer un fichier identique à un document déjà existant : KO
Le message retourné correspond au message pour lg2

**Comment by EmmanuelDemey** [comment]
@PierreVasseur peux tu revoir le dernier point ?

**Comment by PierreVasseur** [comment]
yes
@CatherineGoillot tu peux m'envoyer un fichier pour que je puisse reproduire le problème stp ?

**Comment by CatherineGoillot** [comment]
[TricotonsUnMondeMeilleuModeDEmploi2017.pdf](https://github.com/user-attachments/files/17074562/TricotonsUnMondeMeilleuModeDEmploi2017.pdf)

**Comment by PierreVasseur** [comment]
je n'arrive pas à reproduire le problème, tu pourrais faire une capture d'écran du message d'erreur qui ne va pas stp ?

**Comment by CatherineGoillot** [comment]
Ah je viens de le refaire et j'ai le bon message.
Je vais le refaire avec Emilia mardi et te confirmerai à ce moment là si le message est bon ou si je retrouve le mauvais message.

**Comment by CatherineGoillot** [comment]
Tests refaits ce matin : KO

Quand on essaie de créer un nouveau document avec un fichier existant, on a une erreur 406 et la création n'aboutit pas.
On n'a aucun message spécifié lors de la sauvegarde. Test avec le fichier [bulletin_individuel2016.pdf](https://github.com/user-attachments/files/17127497/bulletin_individuel2016.pdf)

**Comment by EmmanuelDemey** [comment]
Je viens de faire une PR pour résoudre ce problème coté Back.

**Comment by CatherineGoillot** [comment]
Test : OK  

- afficher un message d'erreur lorsque l'utilisateur essaye d'enregistrer avec un libellé lg1 déjà connu : OK
- afficher un message d'erreur lorsque l'utilisateur essaye d'enregistrer un libellé lg2 déjà connu : OK
- afficher un message d'erreur lorsque l'utilisateur essaye d'enregistrer un fichier identique à un document déjà existant : OK
