### ISSUE TITLE
Ergonomie dans la gestion des documents - Possibilité de déposer un document au moment où on est en train de saisir un rapport

### ISSUE THREAD

**Issue by EmmanuelDemey** [InseeFr/Bauhaus#912]
- Afficher le panneau latéral comme pour les zone géographique. 
- Réutiliser le composant de la page Document

**Comment by CatherineGoillot** [comment]
Test : OK

Le clic sur le bouton + affiche bien la fenêtre pour enregistrer un nouveau document.
