### ISSUE TITLE
Rendre toutes les listes déroulantes 'clearable'

### ISSUE THREAD

**Issue by PierreVasseur** [InseeFr/Bauhaus#919]
Sur l'IHM, les listes déroulantes dans les formulaires n'ont pas toutes l'attribut 'clearable' qui permet de supprimer la valeur sélectionnée (cf petite croix à droite du champ)

**Comment by CatherineGoillot** [comment]
Test sur 
- concept : OK
- nomenclature : OK
- opération : en cours
- structure : OK
- liste de codes : OK
- jeux de données : OK
