### ISSUE TITLE
Améliorer le hook useTitle

### ISSUE THREAD

**Issue by PierreVasseur** [InseeFr/Bauhaus#928]
Pendant un laps de temps le titre de la page est **undefined** car les données récupérées (label, ...) du back ne sont pas encore arrivées

**Comment by CatherineGoillot** [comment]
@PierreVasseur   
Merci de nous préciser comment on peut recetter cette carte.

**Comment by PierreVasseur** [comment]
@CatherineGoillot il suffit de vérifier que le titre de la page ne vaut pas "undefined" (pendant un cours laps de temps qui correspond au temps de chargement des données récupérées de l'API) lorsqu'on arrive sur la page de visualisation d'une donnée

**Comment by PierreVasseur** [comment]
NB : le titre de la page c'est ce qui est inscrit dans l'onglet du navigateur

Dans l'exemple du dessous il vaut "Mortalité - Jeux de Données - Bauhaus"
![Image](https://github.com/user-attachments/assets/e514b12f-a6a6-4762-814a-4dd94cd0c342)

**Comment by CatherineGoillot** [comment]
Tests : KO  

- je n'ai jamais le mot "undefined" quand je navigue d'onglets en onglets.  

Mais quand je clique sur Modifier pour les onglets des module Concepts et Opérations, j'ai le mot "créer ..." qui s'affiche.
Exemple, j'affiche un indicateur, je clique sur Modifier et apparaît durant quelques secondes
![Image](https://github.com/user-attachments/assets/90391491-be90-4028-a16e-81f38f0d9c54)

Bon c'est du chipotage mais je ne l'ai pas pour les onglets des autres objets (nomenclature, jeux de données et structure).

**Comment by EmmanuelDemey** [comment]
Je pense que c'est un autre problème, que j'ai également découvert ce matin, que nous avons je pense depuis toujours. Je regarde
