### ISSUE TITLE
Non rafraichissementdes messages d'erreur et non réactivation du bouton "Sauvegarder"

### ISSUE THREAD

**Issue by Emilia-Vittek** [InseeFr/Bauhaus#932]
Lors du test des caractères obligatoires pour chaque formulaire de création dans Bauhaus, à la sauvegarde s'affiche un message d'erreur tant qu'il manque des champs obligatoires à renseigner et le bouton "Sauvegarder" devient inactif. En principe, dès qu'on commence à renseigner un champ obligatoire, le message général d'erreur (bandeau en haut de formulaire) disparaît et le bouton "Sauvegarder" redevient actif.

Il y a **trois cas où cela ne fonctionne pas** et qu'il faudrait corriger, svp : 

- **_module "Opérations"_** : dépôt d'un nouveau document, champ "Fichier"
Ce premier cas est en lien avec le cas relevé par Florian dans la carte "Modification sur création / modification du document" #909

- **_module "Structures"_** : création d'un nouveau composant, champ "Type"

- **_module "Liste de codes"_** : création d'une nouvelle liste de codes partielle, champ "Liste parent"

**Comment by EmmanuelDemey** [comment]
@CatherineGoillot  je ne reproduis pas le problème pour le module Opération.

**Comment by Emilia-Vittek** [comment]
#

**Comment by CatherineGoillot** [comment]
Test : OK

- module Opérations : le message général disparaît et le bouton Sauvegarder est bien actif quand le fichier est déposé.
- module Structure : 
- module Liste de codes : le message général disparaît et le bouton Sauvegarder est bien actif quand le champ est rempli.
