### ISSUE TITLE
Implémenter la déconnexion avec une invalidation du jeton auprès de keycloak

### ISSUE THREAD

**Issue by FBibonne** [InseeFr/Bauhaus#943]
Lors de la déconnexion de l'utilisateur, il faut faire un appel à la ressource `/logout` du serveur keycloak (fonctionnalité fournie par la plupart des librairies OIDC) pour invalider le jeton de l'utilisateur. Cet appel doit se faire en fournissant un paramètre `redirect_uri` vers une route de l'application ne nécessitant d'authentification (tout simplement un écran vide avec "Vous avez été déconnecté")

**Comment by FBibonne** [comment]
@ChristopheYon 
Vu en restitution du rapport d'audit : en plus du bouton logout, il faudrait regarder pour couper la session (au niveau du front en invalidant le jeton keycloak) si l'utilisateur reste inactif trop longtemps. Discuter des rôles pour lesquels c'est à faire et du timeout acceptable et du risque que cela représente.

Dans tous les cas, il faut **ajouter une page non authentifiée** pour rediriger l'utilisateur après la déconnexion (appel du endpoint keycloak d'invalidation du jeton)

**Comment by PierreVasseur** [comment]
Fait dans la PR #973 :
- invalidation du jeton utilisateur avec la librairie oidc-spa
- page "non authentifié" avec bouton **Login**

Reste à faire : 
- déconnexion suite à une période d'inactivité

**Comment by CatherineGoillot** [comment]
Tests : OK 

- bouton déconnexion déconnecte bien l'utilisateur
- sur cette page, un bouton "se connecter" dirige bien l'utilisateur sur la page d'accueil BAUHAUS
