### ISSUE TITLE
Premier message à la saisie d'un nouveau concept

### ISSUE THREAD

**Issue by PierreVasseur** [InseeFr/Bauhaus#963]
**Carte démarrée le 3 septembre 2024**
Actuellement dans le module Concepts, après un clic sur "Nouveau", pour créer un nouveau concept, l'utilisateur voit s'afficher un message avec les champs obligatoires matérialisés, des précisions sous chaque champs et un message d'erreur au-dessus, en haut du formulaire qui est : "Vous avez des erreurs dans ce formulaire".

Ce message a un sens dès que l'utilisaeur veut sauvegarder le concept, s'il n'a pas rempli tous les champs obligatoires correctement.

Mais, il n'a pas de sens à l'ouverture du formulaire de saisie. Par conséquent, est-il possible qu'au clic sur "Nouveau", le message soit "**Remplir les champs requis, matérialisés par * pour pouvoir sauvegarder ce concept**" et que nous n'ayons le message sur les erreurs qu'après une première tentative de sauvegarde, svp ? (avec l'astérisque en rouge)

**Comment by PierreVasseur** [comment]
J'imagine qu'on souhaite la même chose pour les Collections ? @Emilia-Vittek

**Comment by CatherineGoillot** [comment]
Bjr,
Oui, effectivement, il faut le même message.

**Comment by CatherineGoillot** [comment]
test : OK

Le message est correct. 
Après on verra pour harmoniser tous les messages pour tous les objets.
