### ISSUE TITLE
Lenteur à la suppression d'un jeu de données

### ISSUE THREAD

**Issue by flo7894** [InseeFr/Bauhaus#980]
Lors de la suppression d'un jeu de données l'ihm mouline entre 5s et 10s. Ces lenteurs semblent dû à une succession d'erreur 404 sur des GET de la ressource qui vient d'être supprimée.

![Image](https://github.com/user-attachments/assets/29e8cecc-61c6-4461-a060-14a1d68a51f0)

**Comment by EmmanuelDemey** [comment]
Je viens de corriger ce point. Il était également présent sur la suppression des distributions.
