### ISSUE TITLE
Avoir des url différentes pour l'aide selon les instances de bauhaus

### ISSUE THREAD

**Issue by flo7894** [InseeFr/Bauhaus#983]
Sur les prod/qf : 
- Aide "concepts" : https://inseefr.github.io/Bauhaus/fr/guides/user-guide/concept/ 
- Aide "concepts" : https://metadonnees.gitlab-pages.insee.fr/rmes/offre-de-service-rmes/#pages/operation-aide

Sur la demo du ssp-cloud : 
- Aide "concepts" : https://inseefr.github.io/Bauhaus/fr/guides/user-guide/concept/ 
- Aide "concepts" : https://inseefr.github.io/Bauhaus/fr/guides/user-guide/operation/

**Comment by CatherineGoillot** [comment]
Tests : KO

- pour la QF/Prod, redirection OK
- pour le SSP Cloud, la redirection pour les opérations n'est pas bonne. 
  On est dirigé sur https://metadonnees.gitlab-pages.insee.fr/rmes/offre-de-service-rmes/#pages/operation-aide au lieu de https://inseefr.github.io/Bauhaus/fr/guides/user-guide/operation/

**Comment by EmmanuelDemey** [comment]
C'est normal. Cela n'a pas encore été déployé sur la version Cloud.

D'où notre question récemment qu'elle était le meilleur moment pour faire ce déploiement ?

**Comment by CatherineGoillot** [comment]
Désolée de ne pas avoir répondu plus tôt.

C'est déployé : OK
